### ISSUE TITLE
Browsersync not working with HTML Min enabled

### ISSUE THREAD

**Issue by patrickhoehn** [jimblue/statamic-addon-htmlmin#2]
This is just a minor issue as HTML Min is not needed in development env but it took me some time to figure out why Browsersync stopped working without any error message. Maybe something that could be mentioned in your docs?

**Comment by jimblue** [comment]
Thank you @patrickhoehn but it's perfectly working with Webpack Dev Server and without more information about your issue, I don't think it's worth mentioning in the doc.
